<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'name' => 'Gorgon War Pick',
                'entries' => 'This war pick is made from the metal armor of a gorgon and designed in its visage. You gain a +2 bonus to attack and damage rolls made with this magic weapon. If you move at least 20 feet straight toward a target and then hit it with this weapon on the same turn, that target takes an extra 1d6 piercing damage from the attack.  When you roll a 20 on an attack roll against a creature with this weapon, the war pick\'s metal emits a small plume of weakened gorgon breath. When it does, the target\'s body begins to stiffen, and it takes a cumulative –10 foot penalty to its speed until it finishes a short or long rest, or until it\'s targeted by the lesser restoration spell or similar magic. This penalty can\'t reduce a creature\'s speed lower than 5 feet. "Come at me, anyone!" Boasted the champion. His red silk tunic remained spotless, despite the number of combats he\'d been in that day.  A halfling man in ill-fitting leather armor walked into the arena. His weapon, a war pick, was almost as tall as he was. "Aww, and',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 8,
                'source_id' => 1,
                'rarity_id' => 3,
                'user_id' => 2,
                'created_at' => '2024-10-22 10:51:29',
                'updated_at' => '2024-10-22 10:51:29',
                'image' => 'images/kpfZM3AVK09Rr2ivjYhMKPDnpmW5Q2OIczMIXO8d.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Amulet of Health',
                'entries' => 'Your Constitution score is 19 while you wear this amulet. It has no effect on you if your Constitution is already 19 or higher without it.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 3,
                'user_id' => 2,
                'created_at' => '2024-10-22 15:44:40',
                'updated_at' => '2024-10-22 15:44:40',
                'image' => 'images/RqHye7btU7siefEv8nnhhiQIKwltHRltXena75GI.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Mithral Armor',
                'entries' => 'Mithral is a light, flexible metal. A mithral chain shirt or breastplate can be worn under normal clothes.  If the armor normally imposes disadvantage on Dexterity (Stealth) checks or has a Strength requirement, the mithral version of the armor doesn\'t.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 1,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 2,
                'created_at' => '2024-10-22 15:50:33',
                'updated_at' => '2024-10-22 15:50:33',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Circlet of Blasting',
                'entries' => 'While wearing this circlet, you can use an action to cast the scorching ray spell with it. When you make the spell\'s attacks, you do so with an attack bonus of +5. The circlet can\'t be used this way again until the next dawn.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 2,
                'created_at' => '2024-10-22 15:51:55',
                'updated_at' => '2024-10-22 15:51:55',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Vicious Weapon',
                'entries' => 'When you roll a 20 on your attack roll with this magic weapon, the target takes an extra 7 damage of the weapon’s type.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 8,
                'source_id' => 2,
                'rarity_id' => 3,
                'user_id' => 2,
                'created_at' => '2024-10-22 15:52:35',
                'updated_at' => '2024-10-22 15:52:35',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Sword of Sharpness',
                'entries' => 'When you attack an object with this magic sword and hit, maximize your weapon damage dice against the target.  When you attack a creature with this weapon and roll a 20 on the attack roll, that target takes an extra 14 slashing damage. Then roll another d20. If you roll a 20, you lop off one of the target\'s limbs, with the effect of such loss determined by the GM. If the creature has no limb to sever, you lop off a portion of its body instead.  In addition, you can speak the sword\'s command word to cause the blade to shed bright light in a 10-foot radius and dim light for an additional 10 feet. Speaking the command word again or sheathing the sword puts out the light.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 8,
                'source_id' => 2,
                'rarity_id' => 4,
                'user_id' => 2,
                'created_at' => '2024-10-22 15:56:39',
                'updated_at' => '2024-10-22 15:56:39',
                'image' => 'images/91VS4Nlp82rU1U6pEPv0pn62aYgzsS1Ck1zjk8Gk.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Staff of the Magi',
                'entries' => 'This staff can be wielded as a magic quarterstaff that grants a +2 bonus to attack and damage rolls made with it. While you hold it, you gain a +2 bonus to spell attack rolls. The staff has 50 charges for the following properties. It regains 4d6 + 2 expended charges daily at dawn. If you expend the last charge, roll a d20. On a 20, the staff regains 1d12 + 1 charges.  Spell Absorption. While holding the staff, you have advantage on saving throws against spells. In addition, you can use your reaction when another creature casts a spell that targets only you. If you do, the staff absorbs the magic of the spell, canceling its effect and gaining a number of charges equal to the absorbed spell\'s level. However, if doing so brings the staff\'s total number of charges above 50, the staff explodes as if you activated its retributive strike (see below).',
                'page' => null,
                'reqAttune' => 'requires attunement by a Sorcerer, Warlock, or Wizard',
                'weight' => null,
                'type_id' => 6,
                'source_id' => 2,
                'rarity_id' => 5,
                'user_id' => 2,
                'created_at' => '2024-10-22 16:21:19',
                'updated_at' => '2024-10-22 16:21:19',
                'image' => 'images/YlPcnueP7sK3UdPT2Ldn0jCiWkWNQ5CJRq4CMHsj.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Orb of Dragonkind',
                'entries' => 'Ages past, elves and humans waged a terrible war against evil dragons. When the world seemed doomed, powerful wizards came together and worked their greatest magic, forging five Orbs of Dragonkind (or Dragon Orbs) to help them defeat the dragons. One orb was taken to each of the five wizard towers, and there they were used to speed the war toward a victorious end.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 6,
                'user_id' => 2,
                'created_at' => '2024-10-22 16:27:04',
                'updated_at' => '2024-10-22 16:27:04',
                'image' => 'images/xF7bm5j5J2I3UZhtddnTLMktDBSwzExD3JxyD9LA.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Ersatz Eye',
                'entries' => 'This artificial eye replaces a real one that was lost or removed. While the ersatz eye is embedded in your eye socket, it can’t be removed by anyone other than you, and you can see through the tiny orb as though it were a normal eye.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 9,
                'source_id' => 5,
                'rarity_id' => 1,
                'user_id' => 2,
                'created_at' => '2024-10-22 17:17:18',
                'updated_at' => '2024-10-22 17:17:18',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Pipe of Smoke Monsters',
                'entries' => 'While smoking this pipe, you can use an action to exhale a puff of smoke that takes the form of a single creature, such as a dragon, a flumph, or a froghemoth. The form must be small enough to fit in a 1-foot cube and loses its shape after a few seconds, becoming an ordinary puff of smoke.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 9,
                'source_id' => 5,
                'rarity_id' => 1,
                'user_id' => 2,
                'created_at' => '2024-10-22 17:20:24',
                'updated_at' => '2024-10-22 17:20:24',
                'image' => 'images/PahHKm66VUsa7A86LdVe2zeAhNZJeRk7mMpjrbpT.png',
                'verified' => 1,
            ],
        ];
        foreach ($items as $item) {
            Item::create($item);
        }
    }
}
