<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            [
                'name' => 'Gorgon War Pick',
                'entries' => 'This war pick is made from the metal armor of a gorgon and designed in its visage. You gain a +2 bonus to attack and damage rolls made with this magic weapon. If you move at least 20 feet straight toward a target and then hit it with this weapon on the same turn, that target takes an extra 1d6 piercing damage from the attack.  When you roll a 20 on an attack roll against a creature with this weapon, the war pick\'s metal emits a small plume of weakened gorgon breath. When it does, the target\'s body begins to stiffen, and it takes a cumulative –10 foot penalty to its speed until it finishes a short or long rest, or until it\'s targeted by the lesser restoration spell or similar magic. This penalty can\'t reduce a creature\'s speed lower than 5 feet. "Come at me, anyone!" Boasted the champion. His red silk tunic remained spotless, despite the number of combats he\'d been in that day.  A halfling man in ill-fitting leather armor walked into the arena. His weapon, a war pick, was almost as tall as he was.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 8,
                'source_id' => 1,
                'rarity_id' => 3,
                'user_id' => 1,
                'created_at' => '2024-10-22 10:51:29',
                'updated_at' => '2024-10-22 10:51:29',
                'image' => 'images/kpfZM3AVK09Rr2ivjYhMKPDnpmW5Q2OIczMIXO8d.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Amulet of Health',
                'entries' => 'Your Constitution score is 19 while you wear this amulet. It has no effect on you if your Constitution is already 19 or higher without it.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 3,
                'user_id' => 1,
                'created_at' => '2024-10-22 15:44:40',
                'updated_at' => '2024-10-22 15:44:40',
                'image' => 'images/RqHye7btU7siefEv8nnhhiQIKwltHRltXena75GI.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Mithral Armor',
                'entries' => 'Mithral is a light, flexible metal. A mithral chain shirt or breastplate can be worn under normal clothes.  If the armor normally imposes disadvantage on Dexterity (Stealth) checks or has a Strength requirement, the mithral version of the armor doesn\'t.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 1,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 1,
                'created_at' => '2024-10-22 15:50:33',
                'updated_at' => '2024-10-22 15:50:33',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Circlet of Blasting',
                'entries' => 'While wearing this circlet, you can use an action to cast the scorching ray spell with it. When you make the spell\'s attacks, you do so with an attack bonus of +5. The circlet can\'t be used this way again until the next dawn.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 1,
                'created_at' => '2024-10-22 15:51:55',
                'updated_at' => '2024-10-22 15:51:55',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Vicious Weapon',
                'entries' => 'When you roll a 20 on your attack roll with this magic weapon, the target takes an extra 7 damage of the weapon’s type.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 8,
                'source_id' => 2,
                'rarity_id' => 3,
                'user_id' => 1,
                'created_at' => '2024-10-22 15:52:35',
                'updated_at' => '2024-10-22 15:52:35',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Sword of Sharpness',
                'entries' => 'When you attack an object with this magic sword and hit, maximize your weapon damage dice against the target.  When you attack a creature with this weapon and roll a 20 on the attack roll, that target takes an extra 14 slashing damage. Then roll another d20. If you roll a 20, you lop off one of the target\'s limbs, with the effect of such loss determined by the GM. If the creature has no limb to sever, you lop off a portion of its body instead.  In addition, you can speak the sword\'s command word to cause the blade to shed bright light in a 10-foot radius and dim light for an additional 10 feet. Speaking the command word again or sheathing the sword puts out the light.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 8,
                'source_id' => 2,
                'rarity_id' => 4,
                'user_id' => 1,
                'created_at' => '2024-10-22 15:56:39',
                'updated_at' => '2024-10-22 15:56:39',
                'image' => 'images/91VS4Nlp82rU1U6pEPv0pn62aYgzsS1Ck1zjk8Gk.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Staff of the Magi',
                'entries' => 'This staff can be wielded as a magic quarterstaff that grants a +2 bonus to attack and damage rolls made with it. While you hold it, you gain a +2 bonus to spell attack rolls. The staff has 50 charges for the following properties. It regains 4d6 + 2 expended charges daily at dawn. If you expend the last charge, roll a d20. On a 20, the staff regains 1d12 + 1 charges.  Spell Absorption. While holding the staff, you have advantage on saving throws against spells. In addition, you can use your reaction when another creature casts a spell that targets only you. If you do, the staff absorbs the magic of the spell, canceling its effect and gaining a number of charges equal to the absorbed spell\'s level. However, if doing so brings the staff\'s total number of charges above 50, the staff explodes as if you activated its retributive strike.',
                'page' => null,
                'reqAttune' => 'requires attunement by a Sorcerer, Warlock, or Wizard',
                'weight' => null,
                'type_id' => 6,
                'source_id' => 2,
                'rarity_id' => 5,
                'user_id' => 1,
                'created_at' => '2024-10-22 16:21:19',
                'updated_at' => '2024-10-22 16:21:19',
                'image' => 'images/YlPcnueP7sK3UdPT2Ldn0jCiWkWNQ5CJRq4CMHsj.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Orb of Dragonkind',
                'entries' => 'Ages past, elves and humans waged a terrible war against evil dragons. When the world seemed doomed, powerful wizards came together and worked their greatest magic, forging five Orbs of Dragonkind (or Dragon Orbs) to help them defeat the dragons. One orb was taken to each of the five wizard towers, and there they were used to speed the war toward a victorious end.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 6,
                'user_id' => 1,
                'created_at' => '2024-10-22 16:27:04',
                'updated_at' => '2024-10-22 16:27:04',
                'image' => 'images/xF7bm5j5J2I3UZhtddVQdlotHU6s01bc9J9eRRJn.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Ersatz Eye',
                'entries' => 'This artificial eye replaces a real one that was lost or removed. While the ersatz eye is embedded in your eye socket, it can’t be removed by anyone other than you, and you can see through the tiny orb as though it were a normal eye.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 9,
                'source_id' => 5,
                'rarity_id' => 1,
                'user_id' => 1,
                'created_at' => '2024-10-22 17:17:18',
                'updated_at' => '2024-10-22 17:17:18',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Pipe of Smoke Monsters',
                'entries' => 'While smoking this pipe, you can use an action to exhale a puff of smoke that takes the form of a single creature, such as a dragon, a flumph, or a froghemoth. The form must be small enough to fit in a 1-foot cube and loses its shape after a few seconds, becoming an ordinary puff of smoke.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 9,
                'source_id' => 5,
                'rarity_id' => 1,
                'user_id' => 1,
                'created_at' => '2024-10-22 17:20:24',
                'updated_at' => '2024-10-22 17:20:24',
                'image' => 'images/PahHKm66VUsa7A86LdVe2zeAhNZJeRk7mMpjrbpT.png',
                'verified' => 1,
            ],
            [
                'name' => 'Bolt of Step',
                'entries' => 'Looks like a regular crossbow bolt and can be used with any crossbow. The bolt has one charge, and it activates when fired with a crossbow. As a bonus action, the user can speak the command word and teleport next to the bolt’s location, even in mid-air if the bolt is still flying. The activation lasts for one minute after the bolt has stopped moving. Recharges at dawn.',
                'page' => null,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 8,
                'source_id' => 1,
                'rarity_id' => 3,
                'user_id' => 2,
                'created_at' => '2024-10-30 15:20:20',
                'updated_at' => '2024-11-01 17:44:11',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Mariner\'s Armor',
                'entries' => 'While wearing this armor, you have a swimming speed equal to your walking speed. In addition, whenever you start your turn underwater with 0 hit points, the armor causes you to rise 60 feet toward the surface. The armor is decorated with fish and shell motifs.',
                'page' => null,
                'reqAttune' => null,
                'weight' => 0,
                'type_id' => 1,
                'source_id' => 1,
                'rarity_id' => 2,
                'user_id' => 2,
                'created_at' => '2024-10-30 15:35:23',
                'updated_at' => '2024-11-01 18:28:12',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Instrument of Scribing',
                'entries' => 'This musical instrument has 3 charges. While you are playing it, you can use an action to expend 1 charge from the instrument and write a magical message on a nonmagical object or surface that you can see within 30 feet of you. The message can be up to six words long and is written in a language you know. If you are a bard, you can scribe an additional seven words and choose to make the message glow faintly, allowing it to be seen in nonmagical darkness. Casting *Dispel Magic* on the message erases it. Otherwise, the message fades away after 24 hours. The instrument regains all expended charges daily at dawn.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 1,
                'rarity_id' => 1,
                'user_id' => 1,
                'created_at' => '2024-10-30 15:41:21',
                'updated_at' => '2024-11-01 18:31:15',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Arcane Grimoire',
                'entries' => 'While you are holding this leather-bound book, you can use it as a spellcasting focus for your wizard spells, and you gain a bonus to spell attack rolls and to the saving throw DCs of your wizard spells. The bonus is determined by the book\'s rarity. (+2) You can use this book as a spellbook. In addition, when you use your *Arcane Recovery* feature, you can increase the number of spell slot levels you regain by 1.',
                'page' => null,
                'reqAttune' => 'requires attunement by a wizard',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 6,
                'rarity_id' => 3,
                'user_id' => 1,
                'created_at' => '2024-10-30 15:46:47',
                'updated_at' => '2024-11-01 18:31:16',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Cloak of Shadows',
                'entries' => 'This dark, hooded cloak allows the wearer to blend into the shadows. While wearing this cloak, you have advantage on Stealth checks made in dim light or darkness. Once per short rest, you can use a bonus action to become invisible until the start of your next turn. While invisible in this way, attacking or casting a spell ends the invisibility. Many have tried to unravel the cloak’s origins, but its weave seems to shift under scrutiny.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 1,
                'rarity_id' => 2,
                'user_id' => 1,
                'created_at' => '2024-11-01 09:30:00',
                'updated_at' => '2024-11-01 09:30:00',
                'image' => 'images/l9lEmtHIz6QLO0GPu7xhMNpzmqD4eWKgyJjs3JRe.png',
                'verified' => 1,
            ],
            [
                'name' => 'Ring of the Phoenix',
                'entries' => 'This ornate ring grants its wearer the power of rebirth. When you drop to 0 hit points while wearing this ring, you can use your reaction to regain hit points equal to half your maximum health. This ability recharges at dawn. The ring glows with a faint, fiery aura when its power is ready to use, and many legends say that those who wear it are granted a second chance at life.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 3,
                'source_id' => 1,
                'rarity_id' => 4,
                'user_id' => 1,
                'created_at' => '2024-11-01 09:31:00',
                'updated_at' => '2024-11-01 09:31:00',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Wand of Frost',
                'entries' => 'This slender wand is made of polished silver and topped with a shard of enchanted ice. It has 7 charges, and you can use an action to expend one or more of its charges to cast the *Ray of Frost* spell. For every charge spent, the spell’s range and power increase, creating an arctic chill in its wake. The wand regains 1d6 + 1 expended charges daily at dawn. If you expend the wand’s last charge, roll a d20. On a 1, the wand shatters into a pile of icy fragments.',
                'page' => null,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 7,
                'source_id' => 1,
                'rarity_id' => 3,
                'user_id' => 1,
                'created_at' => '2024-11-01 09:32:00',
                'updated_at' => '2024-11-01 09:32:00',
                'image' => null,
                'verified' => 1,
            ],
            [
                'name' => 'Gauntlets of Ogre Power',
                'entries' => 'While wearing these gauntlets, your Strength score becomes 19. They have no effect if your Strength is already 19 or higher. The gauntlets feel warm to the touch, and they are carved with intricate ogre symbols that glow faintly in dim light, a reminder of their powerful origin.',
                'page' => 171,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 1,
                'created_at' => '2024-11-01 09:33:00',
                'updated_at' => '2024-11-01 09:33:00',
                'image' => 'images/y7PhoXHotQBGo2oDT4UMxdPxpMaZ39pID1ngjEH1.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Staff of the Python',
                'entries' => "You can use an action to speak this staff's command word and throw the staff on the ground within 10 feet of you. The staff becomes a giant constrictor snake under your control and acts on its own initiative count. By using a bonus action to speak the command word again, you return the staff to its normal form in a space formerly occupied by the snake.
                                \n
                                On your turn, you can mentally command the snake if it is within 60 feet of you and you aren't incapacitated. You decide what action the snake takes and where it moves during its next turn, or you can issue it a general command, such as to attack your enemies or guard a location.
                                \n
                                If the snake is reduced to 0 hit points, it dies and reverts to its staff form. The staff then shatters and is destroyed. If the snake reverts to staff form before losing all its hit points, it regains all of them.",
                'page' => 204,
                'reqAttune' => 'requires attunement by a Cleric, Druid, or Warlock',
                'weight' => null,
                'type_id' => 6,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 1,
                'created_at' => '2024-11-01 09:34:00',
                'updated_at' => '2024-11-01 09:34:00',
                'image' => 'images/NaV3ZICMHcBJ5N2M5UpEnDUp0Es9ygYrSFnOZZLY.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Boots of Elvenkind',
                'entries' => 'While you wear these boots, your steps make no sound, regardless of the surface you are moving across. You have advantage on Dexterity (Stealth) checks that rely on moving silently. Crafted by ancient elven artisans, the boots are as light as air, and they shimmer faintly under moonlight.',
                'page' => 155,
                'reqAttune' => null,
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 1,
                'created_at' => '2024-11-01 10:00:00',
                'updated_at' => '2024-11-01 10:00:00',
                'image' => 'images/RtsIcMjaU5E7AGdvMlfIl5QJrzTQz2fzwU7n89Yr.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Bracers of Defense',
                'entries' => 'While wearing these bracers, you gain a +2 bonus to AC if you are wearing no armor and using no shield. These bracers were once worn by a nimble rogue who relied solely on agility and quick reflexes to survive the perils of battle.',
                'page' => 156,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 3,
                'user_id' => 1,
                'created_at' => '2024-11-01 10:01:00',
                'updated_at' => '2024-11-01 10:01:00',
                'image' => 'images/eGNoOqHk2sydKvTpFGykZwkzbD9FyloSRGS0VuxH.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Helm of Telepathy',
                'entries' => 'While wearing this helm, you can use an action to cast the *Detect Thoughts* spell (save DC 13) from it. As long as you maintain concentration on the spell, you can use a bonus action to send a telepathic message to a creature you’re focusing on, or to read its thoughts. The helm was forged by a mind flayer cultist and still resonates with whispers of its past users.',
                'page' => 174,
                'reqAttune' => 'requires attunement',
                'weight' => null,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 1,
                'created_at' => '2024-11-01 10:02:00',
                'updated_at' => '2024-11-01 10:02:00',
                'image' => 'images/IXI3AwNxcp1ocPEnKONhk1EsEhMnzPbfUWil8CF5.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Bag of Holding',
                'entries' => 'This bag has an interior space considerably larger than its outside dimensions, roughly 2 feet in diameter at the mouth and 4 feet deep. The bag can hold up to 500 pounds, not exceeding a volume of 64 cubic feet. If the bag is overloaded, it ruptures and is destroyed. Many adventurers consider this a vital tool, as it holds a wealth of equipment without the burden of weight.',
                'page' => 153,
                'reqAttune' => null,
                'weight' => 15,
                'type_id' => 9,
                'source_id' => 2,
                'rarity_id' => 2,
                'user_id' => 1,
                'created_at' => '2024-11-01 10:03:00',
                'updated_at' => '2024-11-01 10:03:00',
                'image' => 'images/Hlh4fzDVkbR1PMvIOF9Zg9F7SakzyORiVrUhTUZd.jpg',
                'verified' => 1,
            ],
            [
                'name' => 'Dragon Slayer Longsword',
                'entries' => 'You gain a +1 bonus to attack and damage rolls made with this magic weapon. When you hit a dragon with it, the dragon takes an extra 3d6 slashing damage. The sword’s blade glows faintly in the presence of dragons, and tales say it was forged by a legendary blacksmith who sought vengeance on the beasts that destroyed his village.',
                'page' => 166,
                'reqAttune' => null,
                'weight' => 6,
                'type_id' => 8,
                'source_id' => 2,
                'rarity_id' => 3,
                'user_id' => 1,
                'created_at' => '2024-11-01 10:04:00',
                'updated_at' => '2024-11-01 10:04:00',
                'image' => 'images/suPTQRZYIcoE4YonglXd8dYxA1wOkN5z6XDsmVw8.jpg',
                'verified' => 1,
            ],
        ];
        foreach ($items as $item) {
            Item::create($item);
        }
    }
}
